name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      severity:
        description: 'Test severity (critical, high, medium, low)'
        required: false
        default: 'critical'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Use Temurin instead of Adoptium

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew  # This step grants execute permission

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run TestNG tests with severity filter
        run: |
          if [[ "${{ github.event.inputs.severity }}" == "critical" ]]; then
            ./gradlew test -Dtestng.groups=critical  # Run only critical tests
          elif [[ "${{ github.event.inputs.severity }}" == "high" ]]; then
            ./gradlew test -Dtestng.groups=high
          elif [[ "${{ github.event.inputs.severity }}" == "medium" ]]; then
            ./gradlew test -Dtestng.groups=medium
          elif [[ "${{ github.event.inputs.severity }}" == "low" ]]; then
            ./gradlew test -Dtestng.groups=low
          else
            ./gradlew test
          fi

      - name: Generate Allure report
        run: ./gradlew allureReport

      - name: Upload TestNG report as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports/tests/test/index.html  # Path to the TestNG report

      - name: Upload Allure report as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: build/allure-report
